Main screen
fadeevich/companies pull request #1
Opened 2023-07-02 17:27 UTC by Fadeevich21

2023-07-03 05:39 UTC, smileman commented on app/src/main/java/com/example/companies/di/AppModule.kt
> +interface AppBindsModule {
Лучше вынести в отдельный файл сразу и переименовать в ViewModelModule. В дальнейшей различных модулей будет больше и их надо будет разделять

2023-07-03 06:06 UTC, smileman requested changes

2023-07-03 06:06 UTC, smileman commented on build.gradle
> +        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
У меня проект в студии не собрался, выдав такую ошибку
`A problem occurred configuring root project 'companies'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0.
     Required by:
         project :
      > No matching variant of androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0' but:
          - Variant 'apiElements' capability androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')
          - Variant 'runtimeElements' capability androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')
          - Variant 'sourcesElements' capability androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0')`

Можете разобраться и починить?

2023-07-03 06:06 UTC, smileman commented on app/src/main/java/com/example/companies/di/utils/AppScope.kt
> +annotation class AppScope
А этот скоуп используете где-то? Если нет - то можно удалить.

2023-07-03 06:06 UTC, smileman commented on app/src/main/java/com/example/companies/utils/AppComponentUtils.kt
Красивое решение. Плюсую

2023-07-03 06:06 UTC, smileman commented on app/src/main/java/com/example/companies/ui/fragment/main/MainFragment.kt
> +    private val binding get() = _binding!!
Думаю можно одной проперти обойтись и всё

2023-07-03 06:06 UTC, smileman commented on app/src/main/java/com/example/companies/ui/view/CustomNavigationButton.kt
> +        addView(binding.root)
У вас CustomNavigationButton представляет собой CardView + внутрь вы добавляете еще заинфлейченные вьюшки. А в xml-файле в вас корневым элементом идет также CardView.

Итого получается одна CardView внутри другой CardView. Лишний уровень вложенности. 
Для таких случаев есть тег <merge>, который надо использовать в качестве корневого элемента в xml-файлике. Почитайте про него и заиспользуйте.

2023-07-03 06:06 UTC, smileman commented on app/src/main/res/layout/activity_main.xml
> +        app:title="Главная" />
Ну ну ну. В ресурсы выносить все строки надо. А тут ссылаться череp @string/

2023-07-03 06:06 UTC, smileman commented on app/src/main/res/layout/fragment_main.xml
> +        android:subtitle="Посмотрите все компании"
В ресурсы выносить все строки надо. А тут ссылаться череp @string/

2023-07-03 06:06 UTC, smileman commented on app/src/main/res/layout/fragment_main.xml
> +        app:cardCornerRadius="17.5dp"
Зачем дробное значение радиуса?

2023-07-03 07:33 UTC, Fadeevich21 commented on app/src/main/java/com/example/companies/di/AppModule.kt
> +interface AppBindsModule {
Вынес в отдельный файл под названием "ViewModelModule"

2023-07-03 07:34 UTC, Fadeevich21 commented on build.gradle
> +        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
Вроде теперь должно работать. Изменил используемую версию Java с 1.8 на 17

2023-07-03 07:34 UTC, Fadeevich21 commented on app/src/main/java/com/example/companies/di/utils/AppScope.kt
> +annotation class AppScope
Использую в классе AppComponent. Где-то услышал о том, что для Component желательно всегда создавать Scope

2023-07-03 07:36 UTC, Fadeevich21 commented on app/src/main/java/com/example/companies/ui/fragment/main/MainFragment.kt
> +    private val binding get() = _binding!!
Я видел, что Google в объяснении про [ViewBinding](https://developer.android.com/topic/libraries/view-binding#fragments) показывают такой пример использования

2023-07-03 07:41 UTC, Fadeevich21 commented on app/src/main/java/com/example/companies/ui/view/CustomNavigationButton.kt
> +        addView(binding.root)
Исправил. Изменил корневой элемент на merge, а также добавил tag 
```kotlin
tools:parentTag="androidx.cardview.widget.CardView"
```
который используется для удобного отображения xml-файла при работе с ним

2023-07-03 07:41 UTC, Fadeevich21 commented on app/src/main/res/layout/activity_main.xml
> +        app:title="Главная" />
Вынес все строки в ресурсы

2023-07-03 07:41 UTC, Fadeevich21 commented on app/src/main/res/layout/fragment_main.xml
> +        android:subtitle="Посмотрите все компании"
Вынес все строки в ресурсы

2023-07-03 07:42 UTC, Fadeevich21 commented on app/src/main/res/layout/fragment_main.xml
> +        app:cardCornerRadius="17.5dp"
У меня в Figma у скругления также было дробное значение радиуса. Получилось при делении 25 / 2 = 17.5

2023-07-04 14:43 UTC, smileman commented on app/src/main/java/com/example/companies/ui/fragment/main/MainFragment.kt
> +    private val binding get() = _binding!!
Да, но не очень понимаю, какой плюс в таком решении. Оно же от null pointer exception все равно не защищает

2023-07-04 14:46 UTC, smileman commented on app/src/main/res/layout/fragment_main.xml
> +        app:cardCornerRadius="17.5dp"
25 / 2 будет 12,5, а не 17.5

Но не в этом суть. Старайтесь все отступы/паддинги/маргины/радиусы делать четными, а желательно даже кратными 4-м.

Если у вас нечетное значение и тем более дробное - то при отображении на реальных устройствах (с разными плотностями пикселей) может криво и смазанно отображаться, т.к. у вас не попадут размеры в целое кол-во пикселей.

2023-07-04 14:46 UTC, smileman approved these changes

2023-07-04 14:48 UTC, merged